channels:
  - conda-forge
dependencies:
  - r-base=4.0.3
  - r-tidyverse
  - r-essentials
  - r-lubridate
  - r-scales
  - r-flexdashboard
  - r-shiny
  - r-geofacet
  - r-ggpubr
  - r-tidyquant
  - r-mapproj
  - r-reshape2
  - r-threejs