channels:
  - conda-forge
  - r
  - f30a78ec8
dependencies:
  - r-base=3.5
  - r-tidyverse
  - r-essentials
  - r-lubridate
  - r-scales
  - r-flexdashboard
  - r-shiny
  - r-geofacet
  - r-ggpubr
  - r-tidyquant
  - r-mapproj
  - r-reshape2
  - r-threejs
  - r-leaflet
  - r-leaflet.extras
  - r-tilegramsr
  - r-colormap
  - r-openintro
